project:
  type: website

website:
  title: "Co-publications"
  navbar:
    left:
      - href: static-file/index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: morph
    css: styles.css
    toc: true
    



